server:
    port: 8086

    
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/microservices
        username: postgres
        password: 123
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    application:
        name: HOTEL-SERVICE #changes the name of application from UNKNOWN to UserService

eureka:
    instance:
        prefer-ip-address: true
    client:
        fetch-registry: true #true by default
        register-with-eureka: true #true by default
        service-url:
            defaultZone: http://localhost:8761/eureka #url of the eureka server, registers with this url